=== MSwadhin/WT/eShop/data/DTD/UserList.dtd
<!-- <?xml version="1.0"?> -->
<!ELEMENT userList (user*)>
<!ELEMENT user (id,fname,lname,email,password,phone,age,city,type,address)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== MSwadhin/WT/eShop/data/userList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE userList SYSTEM "DTD/UserList.dtd">
<userList>
	<user>
		<id>1</id>
		<fname>Abdullah</fname>
		<lname>Mujahid</lname>
		<email>mujahid.swadhin@gmail.com</email>
		<password>e2fc714c4727ee9395f324cd2e7f331f</password>
		<phone>01924535146</phone>
		<age>24</age>
		<city>dhaka</city>
		<type>seller</type>
		<address>h</address>
	</user>
	<user>
		<id>2</id>
		<fname>Mujahid</fname>
		<lname>Swadhin</lname>
		<email>mujahid_swadhin@yahoo.com</email>
		<password>ab56b4d92b40713acc5af89985d4b786</password>
		<phone>01936252524</phone>
		<age>25</age>
		<city>dhaka</city>
		<type>buyer</type>
		<address>h</address>
	</user>
	<user>
		<id>3</id>
		<fname>Nashik</fname>
		<lname>Khan</lname>
		<email>vizzarch.decor47@gmail.com</email>
		<password>e2fc714c4727ee9395f324cd2e7f331f</password>
		<phone>01924535146</phone>
		<age>32</age>
		<city>dhaka</city>
		<type>seller</type>
		<address></address>
	</user>
	<user>
		<id>4</id>
		<fname>Hello</fname>
		<lname>World</lname>
		<email>hw@gmail.com</email>
		<password>e2fc714c4727ee9395f324cd2e7f331f</password>
		<phone>01924535146</phone>
		<age>26</age>
		<city>khulna</city>
		<type>buyer</type>
		<address></address>
	</user>
	<user>
		<id>5</id>
		<fname>Hello</fname>
		<lname>two</lname>
		<email>ht@gmail.com</email>
		<password>81dc9bdb52d04dc20036dbd8313ed055</password>
		<phone>01925363636</phone>
		<age>27</age>
		<city>khulna</city>
		<type>buyer</type>
		<address></address>
	</user>
	<user>
		<id>6</id>
		<fname>Hello</fname>
		<lname>afsf</lname>
		<email>abcd@gmail.com</email>
		<password>e2fc714c4727ee9395f324cd2e7f331f</password>
		<phone>01212121212</phone>
		<age>32</age>
		<city>dhaka</city>
		<type>buyer</type>
		<address></address>
	</user>
	<user>
		<id>7</id>
		<fname>abcd</fname>
		<lname>efgs</lname>
		<email>ab@gmail.com</email>
		<password>e2fc714c4727ee9395f324cd2e7f331f</password>
		<phone>01924535146</phone>
		<age>21</age>
		<city>khulna</city>
		<type>buyer</type>
		<address></address>
	</user>
	<user>
		<id>8</id>
		<fname>Hello</fname>
		<lname>abc</lname>
		<email>ha@gmail.com</email>
		<password>81dc9bdb52d04dc20036dbd8313ed055</password>
		<phone>01924535146</phone>
		<age>21</age>
		<city>dhaka</city>
		<type>seller</type>
		<address></address>
	</user>
	<user>
		<id>9</id>
		<fname>hi</fname>
		<lname>there</lname>
		<email>ht@hty.com</email>
		<password>81dc9bdb52d04dc20036dbd8313ed055</password>
		<phone>01924535146</phone>
		<age>29</age>
		<city>dhaka</city>
		<type>seller</type>
		<address></address>
	</user>
	<user>
		<id>10</id>
		<fname>ami</fname>
		<lname>tumi</lname>
		<email>at@atu.com</email>
		<password>e2fc714c4727ee9395f324cd2e7f331f</password>
		<phone>01924535146</phone>
		<age>24</age>
		<city>khulna</city>
		<type>buyer</type>
		<address></address>
	</user>
	<user>
		<id>11</id>
		<fname>ak</fname>
		<lname>khan</lname>
		<email>akak@gmail.com</email>
		<password>81dc9bdb52d04dc20036dbd8313ed055</password>
		<phone>01924535146</phone>
		<age>24</age>
		<city>khulna</city>
		<type>buyer</type>
		<address>hey_ksfjal_dsf_f_s_</address>
	</user>
	<user>
		<id>12</id>
		<fname>New</fname>
		<lname>User</lname>
		<email>nu@user.com</email>
		<password>81dc9bdb52d04dc20036dbd8313ed055</password>
		<phone>01925686897</phone>
		<age>23</age>
		<city>dhaka</city>
		<type>seller</type>
		<address>hi 
villa
home
country</address>
	</user>
</userList>
